### PR TITLE
Pass log entry context labels to loki

### PR DESCRIPTION
**Pull request by mpetrunic**

### CODE REVIEW

**Review by JaniAnttonen — APPROVED** [review]

**Comment by JaniAnttonen** [comment]
Thanks, making a new release :)

**Comment by JaniAnttonen** [comment]
Just to be clear, the release in question is `winston-loki@6.0.0-rc.2`. Thanks again guise :3 @mpetrunic @nmlinaric

**Comment by mpetrunic** [comment]
> Just to be clear, the release in question is `winston-loki@6.0.0-rc.2`. Thanks again guise :3 @mpetrunic @nmlinaric

We looked into latest release on npm :)
We would appreciate if you would tag releases on github as well :smile:

**Comment by JaniAnttonen** [comment]
> We would appreciate if you would tag releases on github as well :smile: 
Forgot to do that :)

**Pull request merged**
